UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 10540 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 29806 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 30388 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =32930 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =33436 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =33436 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =39755 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =39836 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =42293 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =48204 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =50654 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =50656 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =50657 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =50658 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =52495 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =52935 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =52954 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =52955 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =53056 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =53448 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =53480 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =55456 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =55456 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =64010 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =67487 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =67923 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =73401 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =73403 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =73546 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =73548 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =75353 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =80798 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =80799 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =80800 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =80801 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =89085 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =98199 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =98200 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =98706 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =100344 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =100388 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =100850 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =103231 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =105748 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =106655 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =110258 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =110347 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =110347 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =112871 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =112871 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =115876 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =117507 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =117955 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =118264 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =118294 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =118974 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =119768 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =119768 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =119841 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =119842 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =119842 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =120191 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =121566 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =121566 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =121577 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =121577 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =121581 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =121581 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =121744 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =121744 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =122760 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =124547 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =124703 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =124703 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =126560 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =127004 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =127237 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =127770 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =127770 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =127770 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =127976 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =128726 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =128726 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =128773 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =129276 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =129276 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =129529 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =129529 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =129529 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =129561 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =131978 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =133077 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =133077 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =136293 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =136293 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =137766 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =138707 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =138715 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =138716 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =138717 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =138743 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =138821 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =138822 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =138823 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =138824 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =138825 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =138828 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =138829 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =138888 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =138890 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =139602 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =139609 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =139797 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =139797 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =143849 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144525 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144527 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =144527 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144529 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144531 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =144531 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144534 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =144534 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144536 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144540 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =144540 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144543 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144549 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =144549 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =144562 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =144564 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144566 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =144566 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144568 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144570 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144572 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144574 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =144574 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144578 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =144580 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =145361 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =145420 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =146881 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =146890 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =147250 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =147489 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =148054 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =148457 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =148457 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =149227 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =149231 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =149715 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =149715 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150187 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =150250 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150297 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150726 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =150726 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150728 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150730 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150734 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150736 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =150736 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150738 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150740 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =150740 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150742 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =150742 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150744 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =150744 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150746 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150748 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =150750 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =150754 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =151289 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =153311 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =153311 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =153563 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =153642 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =153739 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =153753 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =153832 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =154028 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =154031 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =154031 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` =154033 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =154035 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =154035 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =154039 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =154041 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =154041 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =154311 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =155094 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =155294 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =155300 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =155357 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =155705 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =157099 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =157163 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =158165 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =165968 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =171577 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =171577 AND `ID` = 5;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =172128 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =172128 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 3;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 5;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 8;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 11;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =173112 AND `ID` = 13;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 15;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =173112 AND `ID` = 15;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 21;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 26;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 34;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =173112 AND `ID` = 34;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =173112 AND `ID` = 35;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 36;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =173112 AND `ID` = 45;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =173112 AND `ID` = 51;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =83980 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =93105 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =95313 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =95848 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =101778 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =101974 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =105138 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =105190 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =105190 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =105192 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =105192 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =110765 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =114280 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =114761 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =114762 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =122102 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =124428 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =124513 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =126529 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =127609 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =127960 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =128185 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =134431 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` =134431 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =156595 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` = 156595 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID3` = 0 WHERE `CreatureID` = 58765 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =10540 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =31649 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =39654 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =40391 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =42283 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =52924 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` =53069 AND `ID` = 1;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 100850 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 119768 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 150187 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 171577 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 171577 AND `ID` = 5;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 2;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 3;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 5;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 8;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 11;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` = 173112 AND `ID` = 13;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 15;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` = 173112 AND `ID` = 15;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 21;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 26;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 34;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` = 173112 AND `ID` = 34;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` = 173112 AND `ID` = 35;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 36;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 173112 AND `ID` = 45;
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` = 173112 AND `ID` = 51;
UPDATE `creature_equip_template` SET `ItemID1` = 0 WHERE `CreatureID` = 29059 AND `ID` = 1;