
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1805, 0, 94960, 0, 'Hymdall');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1806, 0, 95833, 0, 'Hyrja');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1807, 0, 99868, 0, 'Fenryr');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1808, 0, 95675, 0, 'God-King Skovald');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1809, 0, 95676, 1193, 'Odyn');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1810, 0, 91784, 0, 'Warlord Parjesh');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1811, 0, 91789, 0, 'Lady Hatecoil');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1812, 0, 91797, 0, 'King Deepbeard');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1813, 0, 91808, 0, 'Serpentrix');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1814, 0, 96028, 1492, 'Wrath of Azshara');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1825, 0, 98205, 0, 'Corstilax');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1826, 0, 98207, 0, 'Nal¡¯tira');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1827, 0, 98203, 0, 'Ivanyr');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1828, 0, 98206, 0, 'G¨¦n¨¦ral Xakal');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1829, 0, 98208, 1189, 'Conseiller Vandros');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1832, 0, 98542, 0, 'Amalgam of Souls');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1833, 0, 98696, 0, 'Ilysanna Ravencrest');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1834, 0, 98949, 0, 'Smashspite the Hateful');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1835, 0, 99611, 1204, 'Lord Kur\'talos Ravencrest');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1836, 0, 96512, 0, 'Archidruid Glaidalis');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1837, 0, 103344, 0, 'Oakheart');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1838, 0, 99200, 0, 'Dresaron');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (1839, 0, 99192, 1201, 'Shade of Xavius');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2084, 0, 122967, 0, 'Priestess Alun\'za');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2085, 0, 122965, 0, 'Vol\'kaal');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2086, 0, 122963, 0, 'Rezan');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2087, 0, 122968, 1772, 'Yazma');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2093, 0, 126832, 0, 'Skycap\'n Kragg');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2094, 0, 126848, 0, 'Council o Captains');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2095, 0, 126969, 0, 'Ring of Booty');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2096, 0, 126983, 0, 'Harlan Sweete');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2105, 0, 129214, 0, 'Coin-Operated Crowd Pummeler');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2106, 0, 129227, 0, 'Azerokk');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2107, 0, 129231, 0, 'Rixxa Fluxfume');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2108, 0, 129232, 1707, 'Mogul Razdunk');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2111, 0, 131318, 0, 'Elder Leaxa');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2112, 0, 131383, 0, 'Sporecaller Zancha');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2118, 0, 131817, 0, 'Cragmaw the Infested');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2123, 0, 133007, 1711, 'Unbound Abomination');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2124, 0, 133379, 0, 'Adderis and Aspix');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2125, 0, 133384, 0, 'Merektha');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2126, 0, 133389, 0, 'Galvazzt');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2127, 0, 133392, 0, 'Avatar of Sethraliss');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2130, 0, 134056, 0, 'Aqu\'sirr');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2131, 0, 134063, 0, 'Tidesage Council');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2132, 0, 134060, 0, 'Lord Stormsong');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2133, 0, 134069, 1709, 'Vol\'zith the Whisperer');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2257, 0, 144244, 0, 'Tussle Tonks');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2258, 0, 144246, 0, 'K.U.-J.0.');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2259, 0, 144248, 0, 'Machinists Garden');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2290, 0, 150159, 0, 'King Gobbamak');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2291, 0, 150190, 0, 'HK-8 Aerial Oppression Unit');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2292, 0, 150222, 0, 'Gunker');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2299, 0, 152910, 2016, 'Queen Azshara');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2312, 0, 150712, 0, 'Trixie & Naeno');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2325, 0, 157300, 0, 'Tunk');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2326, 0, 156501, 0, 'Ravnyr');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2327, 0, 156523, 0, 'Maut');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2328, 0, 156575, 0, 'Dark Inquisitor Xanesh');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2329, 0, 156818, 0, 'Wrathion');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2331, 0, 156866, 0, 'Ra-den the Despoiled');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2333, 0, 157253, 0, 'The Hivemind');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2334, 0, 157620, 0, 'Prophet Skitra');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2335, 0, 157231, 0, 'Shad\'har the Insatiable');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2336, 0, 157354, 0, 'Vexiona');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2337, 0, 157439, 0, 'Carapace of N\'Zoth');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2343, 0, 157602, 0, 'Drest\'agath');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2344, 0, 158041, 0, 'N\'Zoth the Corruptor');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2345, 0, 158328, 0, 'Il\'gynoth, Corruption Reborn');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2356, 0, 162058, 0, 'Ventunax');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2357, 0, 162059, 0, 'Kin-Tara');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2358, 0, 162060, 0, 'Oryphrion');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2359, 0, 162061, 0, 'Devos, Paragon of Loyalty');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2360, 0, 162100, 0, 'Kryxis the Voracious');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2361, 0, 162103, 0, 'Executor Tarvold');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2362, 0, 162102, 0, 'Grand Proctor Beryllia');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2363, 0, 162099, 2117, 'General Kaal');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2364, 0, 162309, 0, 'Kul\'tharok');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2365, 0, 162317, 0, 'Gorechop');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2366, 0, 162329, 0, 'Xav the Unfallen');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2380, 0, 164185, 0, 'Echelon');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2381, 0, 164218, 0, 'Lord Chamberlain');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2382, 0, 164255, 0, 'Globgrog');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2383, 0, 164261, 0, 'Hungering Destroyer');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2384, 0, 164967, 0, 'Doctor Ickus');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2385, 0, 164266, 0, 'Domina Venomblade');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2386, 0, 164267, 2121, 'Stradama Margrave');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2387, 0, 162691, 0, 'Blightbone');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2388, 0, 162692, 0, 'Amarth');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2389, 0, 162689, 0, 'Stichflesh');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2390, 0, 166945, 0, 'Nalthor the Rimebinder');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2391, 0, 164451, 0, 'An Affront of Challengers');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2392, 0, 170217, 0, 'Mistcaller');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2393, 0, 164517, 2120, 'Tred\'ova');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2394, 0, 164556, 0, 'The Manastorms');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2395, 0, 164558, 0, 'Hakkar, the Soulflayer');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2396, 0, 166608, 2118, 'Mueh\'zala');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2397, 0, 164567, 0, 'Ingra Maloch');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2398, 0, 164406, 0, 'Shriekwing');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2399, 0, 164407, 0, 'Sludgefist');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2400, 0, 164450, 0, 'Dealer Xy\'exa');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2401, 0, 165408, 0, 'Halkias, the Sin-Stained Goliath');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2403, 0, 165410, 0, 'High Adjudicator Aleez');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2404, 0, 165946, 0, 'Mordretha');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2405, 0, 166644, 0, 'Artificer Xy\'mox');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2407, 0, 167406, 2096, 'Sire Denathrius');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2412, 0, 166969, 0, 'The Council of Blood');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2417, 0, 168113, 0, 'Stone Legion Generals');
INSERT IGNORE `instance_encounters`(`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) VALUES (2418, 0, 165066, 0, 'Huntsman Altimor');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (44, 0, '');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (309, 0, 'instance_zulgurub');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (598, 0, '');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (617, 0, '');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (618, 0, '');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (996, 870, 'instance_terrace_of_endless_spring');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1000, 0, '');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1007, 0, 'instance_scholomance');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1008, 870, 'instance_mogu_shan_vault');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1009, 0, 'instance_heart_of_fear');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1112, 0, 'scenario_pursuing_the_black_harvest');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1131, 0, 'scenario_the_secrets_of_ragefire');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1136, 870, 'instance_siege_of_orgrimmar');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1152, 1116, 'wod_garrisone_horde_lvl1');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1153, 1116, 'instance_Garrison_H3');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1158, 1116, 'wod_garrisone_alliance_lvl1');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1159, 1116, 'instance_Garrison_A3');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1277, 0, '');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1330, 1116, 'instance_Garrison_H2');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1331, 1116, 'instance_Garrison_A2');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1473, 1116, 'instance_Garrison_AS');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1474, 1116, 'instance_Garrison_HS');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1494, 1220, 'scenario_the_violet_hold');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1500, 0, 'scenario_artifact_brokenshore');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1536, 0, 'scenario_artifact_ursocslair');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1539, 0, 'scenario_artifact_tirisfal_glades');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1583, 0, 'scenario_mage_art');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1599, 0, 'scenario_artifact_restoacqusition');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1612, 0, 'scenario_artifact_ruins_of_falanaar');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1651, 0, 'instance_new_karazhan');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1760, 0, '');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1813, 1642, 'scenario_ungol_ruins');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1814, 1642, 'scenario_havenswood');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1879, 1642, 'scenario_jorundall');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1882, 1642, 'scenario_verdant_wilds');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1883, 1642, 'scenario_whispering_reef');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1892, 1642, 'scenario_the_rotting_mire');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1893, 1642, 'scenario_the_dread_chain');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1897, 1642, 'scenario_molten_cay');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1898, 1642, 'scenario_skittering_hollow');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1904, 0, 'scenario_stormwind_extraction');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1906, 1642, 'instance_scenario_zuldazar');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1917, 0, '');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (1955, 0, 'scenario_uncharted_island_tutorial');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2124, 1642, 'scenario_crestfall');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2162, 0, 'instance_torgast_tower_of_the_damned');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2236, 0, 'instance_darkmaul_citadel');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2284, 0, 'instance_sanquine_depths');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2285, 0, 'instance_spires_of_ascension');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2286, 0, 'instance_necrotic_wake');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2287, 0, 'instance_halls_of_attonement');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2289, 0, 'instance_plaguefall');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2290, 0, 'instance_mists_of_tirna_scithe');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2291, 0, 'instance_de_other_side');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2293, 0, 'instance_theater_of_pain');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2296, 0, 'instance_castle_nathria');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2441, 0, 'instance_tazavesh');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2450, 0, 'instance_sanctum_of_domination');
INSERT IGNORE `instance_template`(`map`, `parent`, `script`) VALUES (2453, 0, 'instance_torgast_tower_of_the_damned');
