
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1, 717, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4, 214, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4, 1581, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5, 1, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (8, 1337, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (10, 718, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (33, 14, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (33, 1637, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (34, 215, 67, 'Mulgore, Red Cloud Mesa GY - Mulgore');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (35, 332, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (39, 17, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (39, 400, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (39, 491, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (39, 722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (39, 1637, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (39, 1638, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (89, 1638, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (92, 719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (93, 141, 469, 'Teldrassil, Aldrassil GY - Teldrassil');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (94, 85, 67, 'Tirisfal Glades, Deathknell - Tirisfal Glades');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (97, 209, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (97, 214, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (100, 1, 469, 'Dun Morogh, Anvilmar - Dun Morogh');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (101, 721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (102, 1, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (105, 12, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (106, 717, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (106, 1519, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (106, 5861, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (108, 1477, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (109, 214, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (109, 5287, 0, 'Test stranglethorn');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (189, 2159, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (209, 1176, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (229, 17, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (289, 1497, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (309, 1477, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (389, 33, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (389, 214, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (429, 85, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (429, 796, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (429, 2037, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (469, 719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (512, 141, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (512, 719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (512, 1657, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (512, 3524, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (512, 3525, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (549, 22, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (629, 2057, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (631, 2159, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (636, 1584, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (636, 4926, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (636, 5094, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (649, 332, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (690, 2597, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (709, 14, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (789, 1477, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (849, 2557, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (850, 2437, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (851, 5861, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (852, 1537, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (853, 85, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (869, 2057, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (909, 3430, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (909, 3433, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (909, 3456, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (911, 12, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (911, 40, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (911, 44, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (912, 3430, 0, 'Eversong Woods, Sunstrider Isle - Eversong Woods');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (922, 3455, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (923, 3557, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (924, 3479, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (929, 3698, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (931, 22, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (932, 22, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (935, 3483, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (936, 3698, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (937, 3537, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (938, 2597, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (939, 3702, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (940, 3702, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (971, 3702, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (995, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (996, 22, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (997, 22, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (998, 3698, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1036, 3537, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1037, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1039, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1041, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1042, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1044, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1045, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1046, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1047, 3540, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1048, 3540, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1071, 3520, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1240, 3540, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1242, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1242, 3923, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1243, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1244, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1246, 2597, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1247, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1248, 3540, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1249, 616, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1250, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1251, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1252, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1254, 3540, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1256, 85, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1256, 209, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1258, 3968, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1259, 3968, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1260, 3968, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1263, 3522, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1265, 3459, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1268, 3979, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1271, 3979, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1285, 4197, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1289, 17, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1289, 491, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1289, 722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1292, 4075, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1292, 4131, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1293, 4080, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1294, 4080, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1295, 4019, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1296, 4019, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1297, 4019, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1299, 3523, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1309, 65, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1310, 4494, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1311, 4494, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1312, 3979, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1318, 3979, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1327, 2597, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1337, 495, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1346, 4384, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1347, 4384, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1348, 4384, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1349, 4384, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1350, 4384, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1351, 4384, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1352, 4196, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1361, 4378, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1362, 4378, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1363, 4378, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1364, 4406, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1365, 4406, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1366, 4406, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1375, 12, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1376, 495, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1377, 130, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1378, 14, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1379, 4258, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1399, 4384, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1430, 4709, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1431, 4709, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1432, 17, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1433, 17, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1434, 4709, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1458, 2177, 0, 'Gurubashi Arena - Default Graveyard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1469, 1583, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1469, 1584, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1469, 2677, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1469, 7307, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1471, 6457, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1475, 148, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1476, 406, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1477, 65, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1493, 17, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1494, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1495, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1681, 15, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1692, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1692, 4714, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1693, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1693, 4714, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1694, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1694, 4714, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1695, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1695, 4714, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1696, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1697, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1698, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1699, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1700, 14, 0, 'Durotar, Echo Isles GY - Durotar');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1701, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1701, 4714, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1703, 4720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1714, 4720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1715, 4720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1721, 4815, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1721, 5144, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1721, 5145, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1722, 4815, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1722, 5144, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1722, 5145, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1723, 4815, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1723, 5144, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1723, 5145, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1724, 4815, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1724, 5144, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1724, 5145, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1725, 4815, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1725, 5144, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1725, 5145, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1726, 5031, 469, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1727, 5031, 67, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1728, 5031, 67, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1729, 5031, 469, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1745, 4815, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1745, 5144, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1745, 5145, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1746, 4815, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1746, 5144, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1746, 5145, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1747, 4815, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1747, 5144, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1747, 5145, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1749, 5031, 469, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1750, 5031, 67, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1755, 5723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1755, 5733, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1756, 5088, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1758, 5088, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1779, 5339, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1780, 5339, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1781, 5339, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1782, 5339, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1790, 5088, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1791, 5088, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1792, 5088, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1793, 5088, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1794, 5088, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1795, 5088, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1796, 5088, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1810, 4714, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1811, 4714, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1818, 4945, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1818, 5396, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1818, 5638, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1819, 4945, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1819, 5396, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1819, 5638, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1820, 4945, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1820, 5638, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1821, 4945, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1821, 5396, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1821, 5638, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1822, 4945, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1822, 5396, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1822, 5638, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1823, 5396, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1823, 5638, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1824, 4945, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1824, 5396, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1855, 4709, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1856, 4945, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1856, 5396, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1856, 5638, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1862, 5389, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1863, 5389, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1866, 4706, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1869, 4709, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1961, 4922, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1969, 5339, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (3295, 5736, 0, 'The Wandering Isle, Starting Area GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (3297, 5736, 0, 'The Wandering Isle, Hot Springs GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (3299, 5736, 0, 'The Wandering Isle, Farm Area GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (3301, 5736, 0, 'The Wandering Isle, Temple Town GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (3303, 5736, 0, 'The Wandering Isle, Wind Area Town GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (3305, 5736, 0, 'The Wandering Isle, Staff Forest GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (3307, 5736, 0, 'The Wandering Isle, Bamboo Forest GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (3565, 5956, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4093, 6125, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4143, 5736, 0, 'Shen-zin Su - North Side - Starting Location');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4145, 6067, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4149, 6006, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4219, 4812, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4243, 5963, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4264, 6182, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4276, 5976, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4277, 5976, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4351, 6297, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4355, 5918, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4387, 6214, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4389, 6006, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4473, 6507, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4474, 6507, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4475, 6507, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4476, 6507, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4477, 6507, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4478, 6507, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4490, 6622, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4600, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4600, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4601, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4602, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4602, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4603, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4603, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4604, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4604, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4605, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4605, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4606, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4606, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4607, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4607, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4608, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4608, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4609, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4609, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4610, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4611, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4611, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4647, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4648, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4649, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4650, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4652, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4653, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4654, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4655, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4656, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4657, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4658, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4659, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4663, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4664, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4665, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4668, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4683, 6912, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4688, 4874, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4715, 7025, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4723, 7078, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4724, 122, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4726, 122, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4728, 7078, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4734, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4736, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4737, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4745, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4746, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4749, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4750, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4753, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4755, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4758, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4760, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4791, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4793, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4794, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4795, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4796, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4797, 6719, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4798, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4803, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4804, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4805, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4806, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4807, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4808, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4809, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4810, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4811, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4812, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4813, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4814, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4815, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4816, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4817, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4818, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4819, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4835, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4835, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4836, 7025, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4837, 7025, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4838, 7025, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4839, 7025, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4840, 7025, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4841, 7025, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4843, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4843, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4846, 7004, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4858, 7078, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4859, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4860, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4861, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4862, 6755, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4873, 6941, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4874, 6941, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4875, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4877, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4878, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4881, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4882, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4883, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4884, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4885, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4886, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4887, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4888, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4889, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4890, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4891, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4892, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4902, 6722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4903, 6722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4904, 6722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4905, 5354, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4905, 6722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4906, 6722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4907, 6722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4908, 6722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4909, 6722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4910, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4911, 6720, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4911, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4912, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4913, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4914, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4915, 6662, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4917, 6721, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4920, 5516, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4921, 7004, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4922, 7004, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4929, 6722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4931, 6722, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4943, 7495, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4944, 7495, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4946, 6960, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4946, 7004, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4947, 6932, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4949, 7334, 0, '7.0 Azsuna - (01) Azurewing Repose');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4950, 7334, 0, '7.0 Azsuna - (02) Crumbled Palace');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4951, 7334, 0, '7.0 Azsuna - (03) Ruins of Narthalas');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4952, 7334, 0, '7.0 Azsuna - (04) Shipwreck Arena');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4953, 7334, 0, '7.0 Azsuna - (05) Oceanus Cove');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4954, 7334, 0, '7.0 Azsuna - (06) Illidari Stand');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4983, 7334, 0, '7.0 Azsuna - (07) Rhutvan Passage');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4984, 7334, 0, '7.0 Azsuna - (08) The Lost Orchard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4992, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4993, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4994, 6723, 469, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4995, 6723, 67, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4996, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4997, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (4998, 7541, 67, 'Stormheim - Aggramars Vault GY 1');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5008, 7558, 0, '7.0 Valsharah - Lorlathil (SBV)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5010, 7334, 0, '7.0 Azsuna - (10) Makrana');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5011, 7334, 0, '7.0 Azsuna - (11) Eldranil Lagoon');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5012, 7334, 0, '7.0 Azsuna - (12) Hatecoil Warcamp');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5013, 7334, 0, '7.0 Azsuna - (13)  Farondale');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5014, 7334, 0, '7.0 Azsuna - (14) Llothien Woods');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5015, 7334, 0, '7.0 Azsuna - (15) Timeworn Strand North');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5018, 7541, 469, 'Stormheim - Thorignir Roost GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5019, 7541, 67, 'Stormheim - Stormwing Rookery GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5020, 7541, 0, 'Stormheim - Hreidshallr GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5022, 7545, 0, 'Graveyard HellfireCitadel');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5028, 7541, 469, 'Stormheim - MawofNashal GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5030, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5031, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5032, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5034, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5035, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5036, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5037, 6723, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5038, 7541, 0, 'Stormheim - Weeping Bluffs GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5041, 7541, 469, 'Stormheim - Valdisdall');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5045, 7558, 0, '7.0 Valsharah - Bradensbrook (SBV)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5063, 7558, 469, '7.0 Valsharah - Thastalah Basin (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5064, 7558, 67, '7.0 Valsharah - Field of Dreamers (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5065, 7558, 469, '7.0 Valsharah - Starsong Refuge (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5066, 7558, 0, '7.0 Valsharah - Temple of Elune (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5067, 7558, 67, '7.0 Valsharah - Shalanir (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5068, 7558, 67, '7.0 Valsharah - Andutalah (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5069, 7558, 469, '7.0 Valsharah - Tangled Cleft (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5070, 7558, 0, '7.0 Valsharah - Emerald Bay (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5071, 7558, 469, '7.0 Valsharah - Lunarwing Shallows (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5073, 7541, 0, 'Stormheim - Stony Highlands');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5079, 7541, 67, 'Stormheim - Kvaldir Bay GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5082, 7705, 0, '7.0 DH-Mardum - (01) Start');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5083, 7705, 0, '7.0 DH-Mardum - (03) Seat of Command');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5094, 7541, 0, 'Stormheim - Skold Ashil GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5109, 7503, 67, 'Highmountain - Mesa GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5110, 7558, 67, '7.0 Valsharah - Heroes Rest (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5116, 7541, 469, 'Stormheim - RavenbearGY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5119, 7705, 0, '7.0 DH-Mardum - (04) Illidari Foothold');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5140, 7705, 0, '7.0 DH-Mardum - (05) Volcano');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5184, 7541, 0, 'Stormheim - Mystics Graveyard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5185, 7541, 469, 'Stormheim - Alliance Secondary Hub GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5186, 7541, 67, 'Stormheim - Horde Secondary Hub GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5187, 7541, 67, 'Stormheim - Bronzeleaf Thicket GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5188, 7705, 0, '7.0 DH-Mardum - (06) The Fel Hammer');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5189, 7541, 0, 'Stormheim - Brewery GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5201, 7503, 67, 'Highmountain - Riverbend - Rivermane - IntroGY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5202, 7503, 67, 'Highmountain - Bloodhunt Highland - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5203, 7503, 0, 'Highmountain - Shipwreck Cove - Murloc GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5204, 7503, 0, 'Highmountain - Feltotem Coast - Hub GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5205, 7503, 469, 'Highmountain - Thundertotem - Graveyard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5206, 7503, 469, 'HighMountain - Skyhorn - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5207, 7503, 469, 'HighMountain - Nesingwarys Retreat - Graveyard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5208, 7503, 0, 'Highmountain - Prepfoot Compound - Graveyard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5209, 7503, 469, 'Highmountain - Rockaway Coast - MurlocVinetteGY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5216, 7503, 469, 'Highmountain - LonehoofWatch - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5217, 7334, 67, 'Highmountain - FrosthoofWatch - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5217, 7503, 67, 'Highmountain - FrosthoofWatch - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5284, 7705, 0, '7.0 DH-Mardum - (02) Molten Shore');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5287, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5431, 7541, 0, 'Stormheim-GalebrokenPath-1');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5435, 7334, 469, 'Highmountain - Thundertotem Cave - Graveyard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5435, 7503, 469, 'Highmountain - Thundertotem Cave - Graveyard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5460, 7334, 67, 'Highmountain - Trueshot Lodge - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5460, 7503, 67, 'Highmountain - Trueshot Lodge - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5495, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5496, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5497, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5498, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5551, 7334, 67, 'Highmountain - Skyhorn - Northern GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5551, 7503, 67, 'Highmountain - Skyhorn - Northern GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5552, 7334, 67, 'Highmountain - Path of Huln - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5552, 7503, 67, 'Highmountain - Path of Huln - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5584, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5588, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5589, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5590, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5591, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5592, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5593, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5594, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5595, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5597, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5598, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5599, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5601, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5602, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5604, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5606, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5609, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5610, 7334, 0, '7.0 Azsuna - (17) Isle of the Watchers East');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5612, 7334, 0, '7.0 Azsuna - (18) Isle of the Watchers North');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5613, 7334, 0, '7.0 Azsuna - (16) Isle of the Watchers Central');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5614, 7334, 0, '7.0 Azsuna - (19) Timeworn Strand South');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5618, 7541, 469, 'Stormheim - Storms Reach North - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5620, 7541, 67, 'Stormheim - Storms Reach South - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5621, 7334, 0, '7.0 Azsuna - (20) Illidari Perch');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5647, 7558, 67, '7.0 Valsharah - Grizzleweald (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5648, 7558, 0, '7.0 Valsharah - The Dreamgrove (CAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5650, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5651, 7541, 0, 'Stormheim - Shields Rest Island');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5652, 7334, 0, '7.0 Azsuna - (21) Timeworn Strand Underwater');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5675, 7334, 0, '7.0 Azsuna - (22) Rhutvan Divide');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5676, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5687, 8026, 0, 'Emerald Nightmare');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5709, 7541, 0, 'Stormheim - Watchmans Rock GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5733, 7543, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5745, 7334, 0, '7.0 Azsuna - (23) Eldranil Peak');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5758, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5763, 7558, 469, '7.0 Valsharah - Starstalkers Point (IAG)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5764, 7334, 67, 'Highmountain - The Ettinwalk - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5764, 7503, 67, 'Highmountain - The Ettinwalk - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5767, 7334, 67, 'Highmountain - Sunfrost Glade - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5767, 7503, 67, 'Highmountain - Sunfrost Glade - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5768, 7541, 0, 'Stormheim - Blackhawks Bulwark GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5780, 7334, 0, '7.0 Azsuna - (24) Seabreak Isle');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5781, 7334, 0, '7.0 Azsuna - (26) Eye of Azshara W');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5781, 7578, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5782, 7334, 0, '7.0 Azsuna - (25) Eye of Azshara E');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5782, 7578, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5855, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5856, 7334, 0, '7.0 Azsuna - (21) Temple of a Thousand Lights');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5858, 7637, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5939, 7543, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5986, 7543, 0, '');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (5989, 8500, 0, '[DNU] Nazmir, Frogmarsh Graveyard - GY - JMC');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6021, 8574, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6034, 8500, 0, '[DNU] Nazmir, Bat Caves - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6101, 8574, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6102, 8899, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6103, 8701, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6112, 8701, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6116, 8701, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6126, 8574, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6127, 8574, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6162, 8899, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6174, 8899, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6175, 8899, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6200, 8574, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6203, 9126, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6205, 9102, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6206, 9128, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6207, 9100, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6208, 9127, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6209, 9180, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6211, 8701, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6212, 8701, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6213, 8701, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6214, 8701, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6215, 8701, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6216, 8701, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6271, 8899, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6278, 9295, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6280, 9298, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6281, 9299, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6283, 9297, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6284, 9300, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6286, 9296, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6288, 8638, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6289, 8638, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6290, 8638, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6291, 8638, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6292, 8638, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6293, 8638, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6294, 8638, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6295, 8638, 0, NULL);
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6383, 9327, 0, 'Tol Dagor Dungeon');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6459, 8500, 0, '[UNUSED AT THIS TIME] Nazmir, Plateau Azerite - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6497, 8978, 0, '8.0 Tol Dagor - (01) Tol Dagor');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (6936, 10290, 0, 'Dungeon - Mechagon - 01 Entrance Target');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7111, 10238, 67, 'Nazjatar, Horde Start (Horde Only) - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7112, 10327, 469, 'Nazjatar, Alliance Start (Alliance Only) - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7226, 11396, 0, 'Nazjatar, Stone Forest - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7243, 10418, 0, 'Dungeon - Mechagon - 01 Entrance');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7363, 10535, 0, 'Nazjatar, Gorgonian Overlook - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7364, 10335, 0, 'Nazjatar, Ashen Strand - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7365, 10354, 0, 'Nazjatar, Zanj\'ir Terrace - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7366, 10361, 0, 'Nazjatar, Deepcoil Tunnels - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7367, 10346, 0, 'Nazjatar, Highborne Estates - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7368, 10345, 0, 'Nazjatar, The Drowned Market - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7369, 10340, 0, 'Nazjatar, Coral Forest - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7370, 10332, 67, 'Nazjatar, Newhome (Horde Only) - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7371, 10332, 469, 'Nazjatar, Mezzamere (Alliance Only) - GY');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (7800, 10424, 0, 'Exiles Reach - Ogre Ruins');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (8000, 10522, 0, 'Nyalotha Dungeon (NzothRaid)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (8000, 12877, 0, 'Nyalotha Dungeon (NzothRaidMain)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (8001, 7814, 0, 'DH Vault of Wardens');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (8003, 12952, 0, 'Allied DK graveyard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (8004, 10424, 0, 'Exiles Reach - Default Graveyard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (8005, 10581, 0, 'Darkmaul Citadel Dungeon graveyard');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (13224, 13224, 0, 'Revendreth - Castle Nathria - Default');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (20001, 10534, 0, 'Bastion #1');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (20002, 11462, 0, 'Maldraxxus - Theater of Pain');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (20003, 11510, 0, 'Ardenweald #1');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (20004, 10413, 0, 'Revendreth - The Banewood');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (20005, 13332, 0, 'The Maw - Crucible of the Damned');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (20006, 13332, 0, 'The Maw - Crucible of the Damned (start quest chain)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (20007, 10052, 0, 'Nazjatar - The Hanging Reef');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (20008, 11400, 0, 'The Maw - Crucible of the Damned (After The Maw)');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (91000, 10565, 0, 'Oribos');
INSERT IGNORE `graveyard_zone`(`ID`, `GhostZone`, `Faction`, `Comment`) VALUES (1000000, 12952, 0, 'Icecrown Citadel - Allied Race DK Intro - GY');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (2373, 2373, -1293.32, 772.995, 7251.12, 5.602, 'Empyrean Domain - Alliance');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (2374, 2373, -1200.29, 680.177, 7251.71, 2.364, 'Empyrean Domain - Horde');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (7800, 2175, 242.844, -2385.38, 84.6175, 4.99, 'Exiles Reach - Ogre Ruins');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (8000, 2217, -17.143, -49.451, -251.088, 3.11, 'Nyalotha Dungeon - Default Graveyard');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (8001, 1468, 4325.46, -620.53, -281.4, 1.51756, 'DH Vault of Wardens - Default Graveyard');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (8003, 2297, 498.145, -2124.43, 840.857, 3.0651, 'Allied DK - Default Graveyard');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (8004, 2175, -446.1, -2607.1, 0.48, 0.103, 'Exiles Reach - Default Graveyard');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (8005, 2236, 911.062, -1765.29, 181.19, 3.678, 'Darkmaul Citadel Dungeon graveyard');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (9000, 2296, -1864.95, 6940.83, 4290.24, 4.759, 'Castle Nathria - Default');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (9001, 2286, -3314.75, -3798.13, 6603.15, 1.542, 'Necrotic Wake - Entrance Target');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (9002, 2285, -1322.16, -6130.49, 7067.03, 5.52, 'Spires of Ascension - Default');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (9003, 2289, 1984.75, -3205.61, 3261.43, 4.114, 'Plaguefall - Default');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (9004, 2293, 2679.32, -2546.09, 3292.85, 0.053, 'Theater of Pain - Default');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (10413, 2284, -1397.51, 6563.97, 4114.8, 4.12, 'Sanguine Depths - Default');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (10995, 2287, -2209.24, 5027.96, 4140.5, 1.6, 'Halls of Attonement - Default');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (11510, 2291, 3015.16, -2221.95, 5.498, 3.133, 'De Other Side - Default');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (13224, 2222, -1900.55, 6836.43, 4288.43, 4.725, 'Revendreth - Castle Nathria - Default');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (13332, 2364, 4630.18, 6783.45, 4869.12, 2.695, 'The Maw - Venari\'s Refuge');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (13397, 2290, -7011.7, 2069.93, 5519.42, 5.034, 'Mists of Tirna Scithe - Default');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (20001, 2222, -3281.74, -5243.7, 6590.1, 3.831, 'Bastion #1');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (20002, 2222, 2551.51, -2636.38, 3305.73, 5.583, 'Maldraxxus - Theater of Pain');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (20003, 2222, -6180.41, 1620.61, 5582.02, 3.871, 'Ardenweald #1');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (20004, 2222, -3062.27, 6981.55, 4030.14, 2.613, 'Revendreth - The Banewood');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (20005, 2222, 4153.6, 7890.13, 4971.81, 1.264, 'The Maw - Crucible of the Damned');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (20006, 2364, 4153.6, 7890.13, 4971.81, 1.264, 'The Maw - Crucible of the Damned (start quest chain)');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (20007, 1718, 1124.89, -467.966, -297.24, 3.741, 'Nazjatar - The Hanging Reef');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (20008, 2222, 4153.6, 7890.13, 4971.81, 1.264, 'The Maw - Crucible of the Damned (After The Maw)');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (36218, 2222, -1900.89, 6835.92, 4288.43, 1.576, 'Castle Nathria - Exit Target');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (90002, 2285, -1318.02, -6133.89, 7067.03, 5.483, 'Spires of Ascension - Default');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (91000, 2222, -1834, 1542, 5275, 4.71239, 'Oribos GY');
INSERT IGNORE `world_safe_locs`(`ID`, `MapID`, `LocX`, `LocY`, `LocZ`, `Facing`, `Comment`) VALUES (1000000, 2297, 544.549, -2124.7, 840.857, 3.14191, 'Icecrown Citadel - Allied Race DK Intro - GY');
