
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (418, 62, 62, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (431, 64, 64, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (433, 14, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (434, 13, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (435, 11, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (436, 10, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (437, 9, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (438, 8, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (439, 6, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (440, 5, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (441, 4, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (442, 1, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (443, 0, 28, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (444, 0, 25, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (445, 0, 27, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (446, 0, 26, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (447, 0, 24, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (448, 0, 23, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (449, 0, 21, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (450, 0, 18, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (451, 0, 20, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (452, 0, 19, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (453, 0, 17, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (454, 0, 15, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (468, 0, 16, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (469, 0, 22, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (470, 2, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (471, 3, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (472, 7, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (473, 12, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (2137, 0, 0, 44175, 26917, 'Glory of the Raider (10 player)', 'Champion, $B$BWord has traveled to Wyrmrest Temple of the great deeds you have accomplished since arriving in Northrend. $B$BYour bravery should not go unrecognized. Please accept this gift on behalf of the Aspects. Together we shall rid Azeroth of evil, once and for eternity. $B$BAlexstrasza the Life-Binder.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (2138, 0, 0, 44164, 24380, 'Glory of the Raider (25 player)', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (2398, 0, 0, 0, 32842, 'WoW\'s 4th anniversary!', 'Do you know that the World of Warcraft is now four years old? $B$BWe wanted to send you something to say thanks for sharing this game with us. Sure, the 4th anniversary present is traditionally \"flowers\"... but in WoW, it\'s \"bear\". $B$BWith that said, please accept this furry little friend! Just remember to hold his fish by the tail, not the body... that mouth is bigger than it looks. $B$BThe WoW Dev Team.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (3636, 0, 0, 0, 24380, 'Jade Tiger', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (4400, 0, 0, 0, 32842, 'WoW\'s 5th anniversary!', 'Wow, another year has gone by for WoW! $B$BWe wanted to thank you again for continuing to play World of Warcraft with us. In celebration of our 5th year online, we decided to bring back our first raid encounter, the black dragon Onyxia. $B$BTo help remember the event, you are now the proud owner of your very own Onyxian Whelpling. We suggest you bring the little guy out whenever you can and say, \"Many whelps! Handle it!\" Your friends won\'t mind. Honest. $B$BThe WoW Dev Team.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (4845, 0, 0, 62900, 24380, 'Glory of the Cataclysm Hero', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (4853, 0, 0, 62901, 24380, 'Glory of the Cataclysm Raider', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (4854, 189, 189, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5116, 229, 229, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5121, 228, 228, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5123, 226, 226, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5325, 0, 194, 70910, 62092, 'Horde War Wolf', 'How many Alliance heads have fallen into the dust by your hand? How many Victories won, enemies crushed, battefields taken? $B$BThe eyes of Hellscream have been upon you, and they are pleased. Ride on proudly, for the Horde! $B$BWarchief Garrosh Hellscream.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5326, 0, 259, 70910, 62092, 'Horde War Wolf', 'How many Alliance heads have fallen into the dust by your hand? How many Victories won, enemies crushed, battefields taken? $B$BThe eyes of Hellscream have been upon you, and they are pleased. Ride on proudly, for the Horde! $B$BWarchief Garrosh Hellscream.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5328, 0, 193, 70909, 61796, 'Alliance War Steed', 'Time and again your skill and bravery have been proven on the field of battle. $B$BYour deeds will not go unrewarded. Ride on proudly, for the Alliance! $B$BYour King.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5329, 260, 0, 70909, 61796, 'Alliance War Steed', 'Time and again your skill and bravery have been proven on the field of battle. $B$BYour deeds will not go unrewarded. Ride on proudly, for the Alliance! $B$BYour King.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5330, 195, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5331, 196, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5332, 197, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5333, 198, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5334, 199, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5335, 200, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5336, 201, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5337, 202, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5338, 0, 217, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5339, 204, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5340, 205, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5341, 206, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5342, 0, 221, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5343, 208, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5344, 223, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5345, 0, 209, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5346, 0, 210, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5347, 0, 211, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5348, 0, 212, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5349, 0, 213, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5350, 0, 214, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5351, 0, 215, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5352, 0, 216, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5353, 0, 218, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5354, 0, 219, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5355, 0, 220, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5356, 0, 222, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5357, 207, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5358, 0, 224, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5359, 203, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5363, 225, 225, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5449, 0, 0, 60869, 24380, 'Rock Lover', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5506, 227, 227, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5767, 258, 258, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5823, 0, 0, 70909, 61796, 'Alliance War Steed', 'Time and again your skill and bravery have been proven on the field of battle. $B$BYour deeds will not go unrewarded. Ride on proudly, for the Alliance! $B$BYour King.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5824, 0, 0, 70910, 62092, 'Horde War Wolf', 'How many Alliance heads have fallen into the dust by your hand? How many Victories won, enemies crushed, battefields taken? $B$BThe eyes of Hellscream have been upon you, and they are pleased. Ride on proudly, for the Horde! $B$BWarchief Garrosh Hellscream.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5827, 267, 267, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5828, 0, 0, 69230, 24380, 'Glory of the Firelands Raider', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5859, 0, 0, 69854, 52823, 'Left Behind', 'I found this locket in the Igneous Depths, near the lava\'s edge. It is not mine, and I know that it does not belong to either of the Arch Druids. Perhaps it belonged to one of the fire druids. $B$BNo matter who its owner, I have no use for it. Please take it as a small token of our appreciation for all you\'ve done for us.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5860, 0, 0, 69838, 40578, 'Please... Just Take It', 'Ever since his brother was taken away. This little creature has been nothing short of a handful. The guardians and I have done everything we can to contain his energy, but our efforts have fallen depressingly short. It is now clear. He wants to be with his brother.It took us nearly an hour to get him contained. Please, take him with you. Perhaps some time outside of this cavern will do him good.      -Farden Talonshrike', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5863, 0, 0, 0, 32842, 'WoW\'s 7th Anniversary!', 'Wow, yet another year has gone by for WoW! $B$BWe wanted to thank you again for continuing to play World of Warcraft with us. With the return of a certain large dragon, this has been a rough year for the world of Azeroth. On the other hand, that means heroes like you are needed more than ever. $B$BGet out there and defend a shattered world! $B$BThe WoW Dev Team.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5866, 0, 0, 69213, 52845, 'A Gift From the Arch Druid', 'Never again will Hyjal shudder beneath the endless forces of Flame. Never again shall the mortal races of the World tremble before the minions of Ragnaros. $B$BNow, thanks to your efforts, they will tremble before Us. $B$BYour heroism on the Molten Front has been instrumental in the fight against the Firelord. You have gathered allies from all over Kalimdor and turned them into an Army. You have fought the minions of Ragnaros... and prevailed. And for that, you have our deepest thanks.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5875, 0, 0, 54810, 28951, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5876, 0, 0, 71140, 28951, 'Please... Just Take It', 'Hello again, Friend!\r\n\r\nThis mischievous little fellow is driving\r\neveryone in the pet store nuts!\r\n\r\nI thought that perhaps you might take\r\nhim along on some of your adventures...\r\nperhaps he\'ll calm down after he\'s seen a\r\nbit of the world.\r\n\r\nYou DO wear a helmet, right...?\r\n\r\n--Breanni', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5877, 0, 0, 71387, 28951, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (5879, 276, 276, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6116, 285, 285, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6131, 0, 0, 0, 32842, 'WoW\'s 8th Anniversary!', 'Wow, yet another year has gone by for WoW! $B$BWe wanted to thank you again for continuing to play World of Warcraft with us. With the return of a certain large dragon, this has been a rough year for the world of Azeroth. On the other hand, that means heroes like you are needed more than ever. $B$BGet out there and defend a shattered world! $B$BThe WoW Dev Team.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6169, 0, 0, 77068, 24380, 'Glory of the Dragon Soul Raider', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6177, 287, 287, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6374, 314, 314, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6375, 0, 0, 90045, 26917, 'Challenge Conqueror: Silver', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6402, 0, 0, 86562, 59822, 'Ling-Ting\'s Herbal Journey', 'Hello there dear! $B$BThis little guy was scratching at the door after you left. I think he\'s taken quite a liking to you. $B$BDo come visit the brewery again some time. I just made more cookies! $B$BAuntie Stormstout.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6544, 303, 303, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6582, 0, 0, 88147, 24380, 'Pro Pet Mob', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6590, 310, 310, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6607, 320, 320, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6716, 0, 0, 83076, 61962, 'Take your quest', 'Go see Cho to validate this quest', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6724, 317, 317, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6734, 309, 309, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6742, 308, 308, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6754, 0, 0, 83772, 61962, 'Take your quest', 'Go see Cho to validate this quest', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6827, 0, 0, 89785, 61962, 'Pandaren Ambassador', 'Hello Traveler! $B$BIt has been a long time since we have seen one so devoted to our local Pandaren factions. You have put in many days of hard work to reach this lofty goal. $B$BTake this token of our appreciation, and know that you are welcome in Pandaria at all times. $B$BLorewalker Cho.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6828, 0, 0, 89785, 61962, 'Pandaren Ambassador', 'Hello Traveler! $B$BIt has been a long time since we have seen one so devoted to our local Pandaren factions. You have put in many days of hard work to reach this lofty goal. $B$BTake this token of our appreciation, and know that you are welcome in Pandaria at all times. $B$BLorewalker Cho.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6846, 0, 0, 83771, 61962, 'Take your quest', 'Go see Cho to validate this quest', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6847, 0, 0, 83777, 61962, 'Take your quest', 'Go see Cho to validate this quest', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6850, 0, 0, 83770, 61962, 'Take your quest', 'Go see Cho to validate this quest', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6855, 0, 0, 83779, 61962, 'Take your quest', 'Go see Cho to validate this quest', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6856, 0, 0, 83780, 61962, 'Take your quest', 'Go see Cho to validate this quest', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6857, 0, 0, 83773, 61962, 'Take your quest', 'Go see Cho to validate this quest', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6858, 0, 0, 83774, 61962, 'Take your quest', 'Go see Cho to validate this quest', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6874, 319, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6926, 316, 316, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6927, 0, 0, 87769, 24380, 'Glory of the Pandaria Hero', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6932, 0, 0, 87773, 24380, 'Glory of the Pandaria Raider', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6941, 0, 224, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (6942, 223, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7284, 311, 311, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7306, 315, 315, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7385, 0, 0, 87528, 73649, 'Honorary Brewmaster Keg', 'Thanks for all your hard work crafting some of the finest brews we\'ve ever had! $B$BAs a token of our appreciation, the other Brewmasters and I have decided to give you this Honorary Brewmaster Keg. $B$BEnjoy! $B$BMama Stormstout.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7479, 318, 318, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7499, 0, 0, 92738, 24380, 'Taming the World', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7500, 0, 0, 85578, 28951, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7501, 0, 0, 89736, 28951, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7509, 0, 319, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7520, 125, 125, 43300, 24380, 'The Loremaster', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7521, 0, 0, 89686, 24380, 'Time to Open a Pet Store', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7612, 321, 321, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7853, 0, 0, 0, 32842, 'WoW\'s 9th Anniversary!', 'Wow, yet another year has gone by for WoW! $B$BWe wanted to thank you for continuing to play World of Warcraft with us. So here\'s a little celebration package to go with your adventures! $B$BThe WoW Dev Team.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7860, 0, 0, 91802, 32216, 'We\'re Going to Need More Saddles', 'I\'ve heard your stables are nearly as extensive as mine, now. Impressive! Perhaps we can help one another...$b$bThis is a gift from Pandaria.$b$bYours again,$bMei', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7862, 0, 0, 91802, 32216, 'We\'re Going to Need More Saddles', 'I\'ve heard your stables are nearly as extensive as mine, now. Impressive! Perhaps we can help one another...$b$bThis is a gift from Pandaria.$b$bYours again,$bMei', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7908, 0, 0, 92744, 66741, 'Aki the Chosen', 'I thought there was no way you could beat me. $B$BI heard whispers of your assent through the ranks of master tamers but I never thought you would make it this far. You are truly a master now. Take this gift as a sign of respect from both me and all the tamers you have defeated along the way. $B$BCongratulations! $B$BAki the Chosen.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7928, 0, 0, 93385, 24380, 'Operation: Shieldwall Campaign', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7929, 0, 0, 93386, 24380, 'Dominance Offensive Campaign', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7934, 0, 0, 93031, 24380, 'Raiding with Leashes', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7939, 0, 0, 93228, 67260, 'Brawler\'s Pass', 'You\'ve gathered quite a following down at Brawl\'gar! I\'m kinda curious to see what your friends can do. $B$BHere\'s an invitation to give out. Let\'s get some new blood in here! $B$BBoss Bazzelflange.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7940, 0, 0, 93195, 67260, 'Brawler\'s Pass', 'You\'ve gathered quite a following down at Brawl\'gar! I\'m kinda curious to see what your friends can do. $B$BHere\'s an invitation to give out. Let\'s get some new blood in here! $B$BBoss Bazzelflange.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7941, 333, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (7942, 0, 333, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8023, 338, 338, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8052, 340, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8055, 0, 340, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8067, 342, 342, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8121, 341, 341, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8124, 0, 0, 93662, 24380, 'Glory of the Thundering Raider', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8293, 0, 0, 97558, 24380, 'Raiding with Leashes II: Attunement Edition', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8300, 0, 0, 94191, 24380, 'Brutal Pet Brawler', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8301, 348, 348, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8302, 0, 0, 98104, 32216, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8304, 0, 0, 98259, 32216, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8306, 351, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8307, 0, 349, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8325, 444, 444, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8335, 0, 0, 93195, 67260, 'Brawler\'s Pass', 'You\'ve gathered quite a following down at Brawl\'gar! I\'m kinda curious to see what your friends can do. $B$BHere\'s an invitation to give out. Let\'s get some new blood in here! $B$BBoss Bazzelflange.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8337, 0, 0, 93228, 67260, 'Brawler\'s Pass', 'You\'ve gathered quite a following down at Brawl\'gar! I\'m kinda curious to see what your friends can do. $B$BHere\'s an invitation to give out. Let\'s get some new blood in here! $B$BBoss Bazzelflange.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8340, 0, 0, 98543, 68323, 'Wraps of the Blood-Soaked Brawler', 'Let\'s take a quick inventory: You\'ve defeated a shark, a robotic crocolisk, a pile of ooze, a pair of penguins, and a whole roomful of deadly brawlers from around the world. $B$BYeah, I\'d say you\'ve earned a shirt.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8343, 0, 0, 98543, 68323, 'Wraps of the Blood-Soaked Brawler', 'Let\'s take a quick inventory: You\'ve defeated a shark, a robotic crocolisk, a pile of ooze, a pair of penguins, and a whole roomful of deadly brawlers from around the world. $B$BYeah, I\'d say you\'ve earned a shirt.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8345, 0, 0, 98618, 32216, 'Hearthsteed', 'This fine magical construct arrived only yesterday, and you were the first adventurer I thought of. $B$BEnjoy! $B$BMei Francis $B$BExotic Mounts $B$BDalaran.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8348, 0, 0, 98715, 24380, 'The Longest Day', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8360, 350, 350, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8392, 163, 163, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8397, 377, 377, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8398, 0, 0, 104246, 73716, 'Ahead of the Curve: Garrosh Hellscream (10 player)', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8399, 0, 0, 104246, 73716, 'Ahead of the Curve: Garrosh Hellscream (25 player)', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8430, 374, 374, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8431, 373, 373, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8432, 371, 371, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8433, 367, 367, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8434, 366, 366, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8436, 368, 368, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8437, 369, 369, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8438, 370, 370, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8439, 372, 372, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8454, 0, 0, 104208, 24380, 'Glory of the Orgrimmar Raider', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8482, 384, 384, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8484, 0, 0, 103533, 24380, 'Grievous Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8485, 0, 0, 103533, 24380, 'Grievous Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8507, 385, 385, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8508, 386, 386, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8509, 387, 387, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8641, 0, 0, 103533, 24380, 'Prideful Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8642, 0, 0, 103533, 24380, 'Prideful Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8643, 378, 378, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8644, 42, 42, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8645, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8646, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8649, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8666, 379, 379, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8667, 42, 42, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8668, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8669, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8670, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8679, 382, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8680, 0, 383, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8721, 389, 389, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8820, 0, 0, 0, 32842, 'WoW\'s 10th Anniversary', 'Can you believe it\'s been ten years? $B$BWe wanted to thank you for joining us in our celebration of the tenth anniversary of World of Warcraft with this adorable fiery fellow. Plucked from the Firelord\'s litter. $B$BThe Wow Dev Team.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8897, 428, 428, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8898, 0, 0, 116791, 24380, 'Challenge Warlord: Silver', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8903, 390, 390, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8965, 442, 442, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8973, 439, 439, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (8985, 0, 0, 116383, 24380, 'Glory of the Draenor Raider', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9016, 391, 391, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9058, 143, 143, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9069, 0, 0, 120121, 24380, 'An Awfully Big Adventure', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9072, 415, 415, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9077, 392, 392, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9078, 394, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9080, 0, 393, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9094, 395, 395, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9169, 0, 0, 93228, 67260, 'Brawler\'s Pass', 'You\'ve gathered quite a following down at Brawl\'gar! I\'m kinda curious to see what your friends can do. $B$BHere\'s an invitation to give out. Let\'s get some new blood in here! $B$BBoss Bazzelflange.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9170, 333, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9173, 0, 0, 93228, 67260, 'Brawler\'s Pass', 'You\'ve gathered quite a following down at Brawl\'gar! I\'m kinda curious to see what your friends can do. $B$BHere\'s an invitation to give out. Let\'s get some new blood in here! $B$BBoss Bazzelflange.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9174, 0, 333, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9176, 0, 0, 98543, 68323, 'Wraps of the Blood-Soaked Brawler', 'Let\'s take a quick inventory: You\'ve defeated a shark, a robotic crocolisk, a pile of ooze, a pair of penguins, and a whole roomful of deadly brawlers from around the world. $B$BYeah, I\'d say you\'ve earned a shirt.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9177, 0, 0, 98543, 68323, 'Wraps of the Blood-Soaked Brawler', 'Let\'s take a quick inventory: You\'ve defeated a shark, a robotic crocolisk, a pile of ooze, a pair of penguins, and a whole roomful of deadly brawlers from around the world. $B$BYeah, I\'d say you\'ve earned a shirt.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9232, 446, 446, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9236, 0, 0, 103533, 24380, 'Primal Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9238, 0, 0, 103533, 24380, 'Primal Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9239, 42, 42, 128277, 29318, 'Gladiator: Warlords Season 1', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9240, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9241, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9242, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9252, 0, 0, 116115, 24380, 'Brood of Alysrazor', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9394, 0, 0, 116651, 24380, 'They Really Love Me!', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9396, 0, 0, 116670, 24380, 'Glory of the Draenor Hero', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9429, 0, 0, 109255, 24380, 'Upgrading the Mill', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9454, 0, 0, 111997, 24380, 'Draenic Seed Collector', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9462, 0, 0, 111928, 24380, 'Draenor Angler', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9463, 0, 0, 111999, 24380, 'Draenic Pet Battler', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9464, 443, 443, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9468, 0, 0, 111977, 24380, 'Salvaging Pays Off', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9470, 420, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9471, 0, 419, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9472, 421, 421, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9473, 0, 422, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9474, 423, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9475, 0, 424, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9476, 425, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9477, 0, 0, 111987, 24380, 'Savage Friends', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9478, 0, 0, 111987, 24380, 'Savage Friends', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9487, 0, 0, 111983, 24380, 'Got My Mind On My Draenor Money', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9495, 0, 0, 111981, 24380, 'The Bone Collector', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9496, 0, 0, 0, 24380, 'Warlord\'s Deathwheel', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9508, 0, 406, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9509, 0, 403, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9510, 0, 400, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9511, 0, 399, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9512, 0, 398, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9513, 0, 402, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9514, 0, 404, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9515, 0, 401, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9516, 412, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9517, 409, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9518, 410, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9519, 408, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9520, 413, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9521, 407, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9522, 411, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9523, 0, 0, 111971, 24380, 'Patrolling Draenor', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9526, 0, 0, 112003, 24380, 'Master of Mounts', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9539, 0, 0, 116668, 24380, 'Advanced Husbandry', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9540, 414, 0, 116781, 24380, 'The Stable Master', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9550, 0, 0, 115484, 24380, 'Boldly, You Sought the Power of Ragnaros', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9565, 0, 0, 111969, 24380, 'Master Trapper', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9566, 0, 418, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9577, 385, 385, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9583, 386, 386, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9589, 387, 387, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9598, 0, 0, 69226, 32216, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9599, 0, 0, 69226, 32216, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9618, 426, 426, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9619, 438, 438, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9620, 429, 429, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9621, 430, 430, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9622, 431, 431, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9623, 432, 432, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9624, 436, 436, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9625, 437, 437, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9626, 433, 433, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9627, 434, 434, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9643, 0, 0, 118577, 28951, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9673, 0, 0, 119215, 24380, 'The Toymaster', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9685, 0, 0, 111866, 24380, 'Draenor Safari', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9696, 0, 0, 140761, 24380, 'Family Familiar', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9705, 0, 0, 116668, 24380, 'Advanced Husbandry', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9706, 0, 414, 116781, 24380, 'The Stable Master', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9713, 0, 0, 118676, 54441, 'Lost Item', 'We discovered this curious item in one of our vaults, and it apparently belongs to you.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9725, 440, 440, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9729, 417, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9738, 406, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9761, 0, 0, 122129, 24380, 'Darkmoon Racer Roadhog', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9764, 0, 0, 122119, 24380, 'Rocketeer: Gold', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9785, 0, 0, 122120, 24380, 'Powermonger: Gold', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9792, 0, 0, 122126, 24380, 'Wanderluster: Gold', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9799, 0, 0, 122128, 24380, 'Big Race Roadhog', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9805, 0, 0, 122125, 24380, 'Big Rocketeer: Gold', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9811, 0, 0, 122121, 24380, 'Big Wanderluster: Gold', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9817, 0, 0, 122124, 24380, 'Big Powermonger: Gold', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9824, 0, 0, 122116, 24380, 'Raiding with Leashes III: Drinkin\' From the Sunwell', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9838, 0, 0, 122293, 24380, 'What A Strange, Interdimensional Trip It\'s Been', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9885, 0, 0, 122122, 24380, 'Ace Tonk Commander', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9894, 0, 0, 122123, 24380, 'Triumphant Turtle Tossing', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9909, 0, 0, 122718, 7406, 'A Most Splendid Convenience', 'Adventurer! Your wondrous deeds have been celebrated all around the world. In gratuity for your great services in preventing the world\'s destruction several times over, I, Oglethorpe Obnoticus, on behalf of the citizens of Azeroth, do hereby present you with the ability to relax no matter where you are traveling!', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9912, 0, 0, 122700, 91589, 'Tunes on the Go', 'You\'re always so busy Commander, so I made you something to take your music on the go. $B$BBehold, the Portable Audiophone! $B$BEnjoy! $B$BSmallie.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9914, 0, 0, 122700, 91072, 'What a Music Collection!', 'So much music, all in one place! $B$BA true music lover like yourself should have some mobile tunes. Music makers conquering worlds just a bit more fun. $B$BThis one\'s on the house! $B$BDrix.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9924, 445, 445, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9983, 0, 0, 123862, 24380, 'That\'s Whack!', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9995, 449, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9996, 448, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9997, 447, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9998, 0, 452, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10000, 0, 450, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10001, 0, 451, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10018, 0, 0, 128706, 24380, 'Draenor Pathfinder', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10043, 457, 457, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10058, 0, 0, 0, 32842, 'WoW\'s 11th Anniversary!', 'Wow, yet another year has gone by for WoW! $B$BWe wanted to thank you for continuing to play World of Warcraft With us, so here\'s an Anniversary Gift to go with your adventures! $B$BThe WoW Dev Team.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10072, 456, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10092, 0, 0, 103533, 24380, 'Wild Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10093, 0, 0, 103533, 24380, 'Wild Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10094, 0, 0, 103533, 29318, 'Warmongering Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10095, 0, 0, 103533, 29318, 'Warmongering Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10096, 453, 453, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10097, 454, 454, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10098, 42, 42, 128281, 29318, 'Gladiator: Warlords Season 2', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10099, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10100, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10101, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10104, 449, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10105, 0, 452, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10106, 448, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10107, 0, 451, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10108, 447, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10109, 0, 450, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10110, 42, 42, 128282, 29318, 'Gladiator: Warlords Season 3', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10111, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10112, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10113, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10116, 447, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10117, 0, 450, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10118, 448, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10119, 0, 451, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10120, 449, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10121, 0, 452, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10149, 0, 0, 127140, 24380, 'Glory of the Hellfire Raider', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10164, 455, 455, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10170, 0, 0, 128353, 83863, 'Seaman', 'Greetings Commander! $B$BIt looks like you are going to have a bright future as naval strategist! $B$BI figured this trinket might be of use on your high seas adventures. Use it anytime you want to quickly return to your shipyard. $B$BKhadgar.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10172, 0, 0, 128363, 93822, 'Petty Officer', 'Captain, $B$BYou have exceeded all of my expectations commanding our fleet. Take this gift as a sign of my gratitude. $B$BWear it with honor. $B$BMerreck Vonder.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10255, 0, 0, 128363, 94789, 'Petty Officer', 'Captain, $B$BYou have exceeded all of my expectations commanding our fleet. Take this gift as a sign of my gratitude. $B$BWear it with honor. $B$BRolosh Wavechaser.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10256, 0, 0, 128365, 93822, 'Charting a Course', 'Admiral, $B$BYou have proven yourself to be an excellent commander of our fleet. Take this gift as a token of my appreciation. $B$BWear it proudly. $B$BMerreck Vonder.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10258, 0, 0, 128365, 94789, 'Charting a Course', 'Admiral, $B$BYou have proven yourself to be an excellent commander of our fleet. Take this gift as a token of my appreciation. $B$BWear it proudly. $B$BRolosh Wavechaser.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10265, 0, 456, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10334, 91, 91, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10354, 85, 85, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10355, 0, 0, 87776, 32216, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10356, 0, 0, 87776, 32216, 'Please...Just take it', 'Here is your reward !', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10412, 0, 0, 140323, 24380, 'Poor Unfortunate Souls', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10609, 476, 476, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10694, 477, 477, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10741, 0, 0, 0, 32842, 'WoW\'s 12th Anniversary!', 'Wow, yet another year has gone by for WoW! $B$BWe wanted to thank you for continuing to play World of Warcraft With us, so here\'s an Anniversary Gift to go with your adventures! $B$BThe WoW Dev Team.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10774, 0, 0, 139773, 40997, 'Hatchling\'s First Flight', 'The great Aviana was quite impressed with your mastery over the winds and currents of the open sky. $B$BAccept this gift with her blessing.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10827, 484, 484, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10850, 485, 485, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10876, 0, 0, 139003, 54441, 'Lost Item', 'We discovered this curious item in one of our vaults, and it apparently belongs to you.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10997, 0, 0, 103533, 29318, 'Vindictive Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (10998, 0, 0, 103533, 29318, 'Vindictive Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11003, 0, 0, 103533, 29318, 'Fearless Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11004, 0, 0, 103533, 29318, 'Fearless Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11005, 0, 0, 103533, 29318, 'Cruel Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11008, 0, 0, 103533, 29318, 'Cruel Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11009, 0, 0, 103533, 29318, 'Ferocious Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11010, 0, 0, 103533, 29318, 'Ferocious Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11011, 42, 42, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11012, 502, 502, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11013, 42, 42, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11014, 504, 504, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11015, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11016, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11017, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11020, 447, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11021, 0, 450, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11022, 448, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11023, 0, 451, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11024, 449, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11025, 0, 452, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11026, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11027, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11028, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11031, 0, 450, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11032, 447, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11033, 0, 451, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11034, 448, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11035, 0, 452, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11036, 449, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11037, 508, 508, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11038, 42, 42, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11039, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11040, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11041, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11044, 0, 451, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11045, 448, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11046, 0, 450, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11047, 447, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11048, 0, 452, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11049, 449, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11050, 449, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11051, 0, 452, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11052, 447, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11053, 0, 450, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11054, 448, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11055, 0, 451, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11058, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11059, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11060, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11061, 42, 42, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11062, 509, 509, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11066, 0, 0, 138387, 97359, 'Underbelly Tycoon', 'We found this creature clawing at an unidentifiable corpse in the back tunnels of the Underbelly, and we were immediately reminded of you. I sincerely hope you find it to your liking. $B$BRaethan.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11139, 483, 483, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11163, 0, 0, 141217, 24380, 'Glory of the Legion Hero', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11175, 0, 0, 140493, 116416, 'Next Course in Higher Dimensional Rifting', 'Congratulations on completing your studies in the  Beginner\'s Guide to Dimensional Rifting. In recognition of your dedication, I\'m enclosing this next volume in the series. $B$BI believe you\'ll find this tome has a bit more reach of material, but I\'ll leave that for your discovery. $B$BSincerely, $B$BMentithus Leytracker.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11176, 0, 0, 140500, 24380, 'Remember to Share', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11180, 0, 0, 141216, 24380, 'Glory of the Legion Raider', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11210, 0, 0, 0, 92219, 'For the Alliance!', 'Decades ago, bloodthristy invaders emerged from the Dark Portal, rampaging through our lands and threatening our very existence. But with might, cunning, and a resolve that forged the Alliance amidst the flames of destruction. Our champions drove them back. Take these arms and bear them with pride. for you are a champion of the alliance!', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11211, 0, 0, 0, 89753, 'For the Horde!', 'We Orcs came to this world decades ago, driven by demonic bloodlust. Pillaging and carving a swath of destruction. Now free of the blood curse. We stand proudly alongside the greatest warriors of azeroth. Defending family and homeland with our dying breath. But we must never forget that dark past. Lest it overtake us once again.Take these arms as a reminder of our origins, the foe we now face, and what it means to be of Horde, Lok\'tar Ogar!', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11232, 486, 486, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11233, 0, 0, 141352, 24380, 'Broken Isles Safari', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11320, 0, 0, 142210, 24380, 'Raiding with Leashes IV: Wrath of the Lick King', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11387, 493, 493, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11427, 0, 0, 143660, 24380, 'No Shellfish Endeavor', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11563, 0, 0, 93195, 24380, 'The Second Rule of Brawler\'s Guild', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11564, 0, 0, 93228, 24380, 'The Second Rule of Brawler\'s Guild', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11565, 333, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11566, 0, 333, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11725, 0, 0, 152583, 108825, 'Jewel of the Tides', 'I fished up this gem in the pond the other day. It doesn\'t seem to be very valuable, and based on my experience, it\'s terrible bait. $B$BI was about to throw it away, but then I thought that you might be interested in having it...', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11761, 505, 505, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11763, 511, 511, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11765, 0, 0, 147543, 24380, 'Pet Battle Challenge: Wailing Caverns', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11781, 506, 506, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11848, 0, 0, 0, 32842, 'WoW\'s 13th Anniversary!', 'Wow, yet another year has gone by for WoW! $B$BWe wanted to thank you for continuing to play World of Warcraft With us, so here\'s an Anniversary Gift to go with your adventures! $B$BThe WoW Dev Team.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11856, 0, 0, 151632, 24380, 'Pet Battle Challenge: Deadmines', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11869, 0, 0, 150372, 23197, 'Arsenal: The Warglaives of Azzinoth', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11941, 510, 510, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (11987, 0, 0, 152815, 24380, 'Glory of the Argus Raider', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12002, 513, 513, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12010, 512, 512, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12031, 0, 0, 103533, 29318, 'Fierce Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12032, 0, 0, 103533, 29318, 'Fierce Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12034, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12035, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12036, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12038, 447, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12039, 448, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12040, 449, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12042, 0, 450, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12043, 0, 451, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12044, 0, 452, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12045, 42, 42, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12078, 0, 0, 152396, 24380, 'Commander of Argus', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12079, 0, 0, 152963, 24380, 'Raiding with Leashes V: Cuteaclysm', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12100, 0, 0, 153040, 24380, 'Family Fighter', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12103, 0, 0, 153041, 24380, '...And Chew Mana Buns', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12104, 516, 516, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12134, 517, 517, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12136, 0, 0, 103533, 24380, 'Dominant Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12137, 0, 0, 103533, 24380, 'Dominant Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12167, 42, 42, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12168, 42, 42, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12169, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12170, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12171, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12174, 0, 451, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12175, 448, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12176, 0, 450, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12177, 447, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12178, 0, 452, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12179, 449, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12185, 519, 519, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12186, 43, 43, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12187, 45, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12188, 44, 44, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12189, 449, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12190, 0, 452, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12191, 447, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12192, 0, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12194, 0, 45, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12195, 448, 0, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12199, 0, 0, 103533, 24380, 'Demonic Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12200, 0, 0, 103533, 24380, 'Demonic Combatant', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12290, 0, 0, 156666, 28951, 'Master Pet Brawler', 'It takes a lot of dedication to beat that many opponents with so many different types of pets. You must be quite the trainer, a master trainer even. $B$BWe\'re proud to bestow upon you this tabard, marking you as a true master of pet brawling. $B$BCongratulations! $B$BBreanni.', 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12412, 522, 522, 0, 0, NULL, NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12431, 0, 0, 156721, 24380, 'Post Haste', NULL, 0);
INSERT IGNORE `achievement_reward`(`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (12439, 521, 521, 0, 0, NULL, NULL, 0);
